Fix whitespace
Prior to this commit the indentation and white space was inconsistant.
This commit fixes that by correcting the indentations to two spaces.

diff --git a/build_deps b/build_deps
--- a/build_deps
+++ b/build_deps
@@ -1,28 +1,28 @@
 #!/bin/bash
 
 function begin_stage() {
-	local stage_name=$1
-	local distfile_mask=$2
+  local stage_name=$1
+  local distfile_mask=$2
 
-	echo -ne "\033]0;${stage_name} stage\007"
-	echo " * Cleaning and unpacking ${stage_name}"
-	rm -rf $WORK/*
+  echo -ne "\033]0;${stage_name} stage\007"
+  echo " * Cleaning and unpacking ${stage_name}"
+  rm -rf $WORK/*
 
-	if echo $distfile_mask | grep -q '\.tgz$' ; then
-		tar -xzf ${DIST}/$distfile_mask -C $WORK
-	elif echo $distfile_mask | grep -q '\.tar\.gz$' ; then
-		tar -xzf ${DIST}/$distfile_mask -C $WORK
-	elif echo $distfile_mask | grep -q '\.tar\.bz2$' ; then
-		tar -xjf ${DIST}/$distfile_mask -C $WORK
-	elif echo $distfile_mask | grep -q '\.tar\.xz$' ; then
-		tar --xz -xf ${DIST}/$distfile_mask -C $WORK
-	elif echo $distfile_mask | grep -q '\.zip$' ; then
-		unzip -d $WORK ${DIST}/$distfile_mask
-	fi
+  if echo $distfile_mask | grep -q '\.tgz$' ; then
+    tar -xzf ${DIST}/$distfile_mask -C $WORK
+  elif echo $distfile_mask | grep -q '\.tar\.gz$' ; then
+    tar -xzf ${DIST}/$distfile_mask -C $WORK
+  elif echo $distfile_mask | grep -q '\.tar\.bz2$' ; then
+    tar -xjf ${DIST}/$distfile_mask -C $WORK
+  elif echo $distfile_mask | grep -q '\.tar\.xz$' ; then
+    tar --xz -xf ${DIST}/$distfile_mask -C $WORK
+  elif echo $distfile_mask | grep -q '\.zip$' ; then
+    unzip -d $WORK ${DIST}/$distfile_mask
+  fi
 
-	pushd $WORK/`echo $distfile_mask | sed 's/\*.*//'`*
-	echo " * Compiling ${stage_name}"
-	sleep $PAUSE
+  pushd $WORK/`echo $distfile_mask | sed 's/\*.*//'`*
+  echo " * Compiling ${stage_name}"
+  sleep $PAUSE
 }
 
 function complete_stage() {
@@ -34,26 +34,26 @@ function complete_stage() {
 }
 
 if [[ ! ${2} ]] ; then
-	echo
-	echo "Pass all build options or use build-* wrappers instead."
-	echo
-	echo "<1 target path> <2 distfiles dir> [3 stage]"
-	echo
-        echo "  Stage 0.1 - OpenMP"
-        echo "  Stage 0.2 - lzma"
-	echo "	Stage 1.1 - boost"
-	echo "	Stage 1.2 - jpeg"
-	echo "	Stage 1.3 - tiff"
-	echo "	Stage 1.4 - png"
-	echo "	Stage 1.6 - ilmbase"
-	echo "	Stage 1.7 - OpenEXR"
-	echo "	Stage 2.1 - OpenImageIO"
-	echo "	Stage 4.1 - Embree"
-	echo "	Stage 4.2 - C-blosc"
-	echo "	Stage 4.3 - TBB"
-	echo "	Stage 4.4 - OpenCL"
-	echo
-	exit 1
+  echo
+  echo "Pass all build options or use build-* wrappers instead."
+  echo
+  echo "<1 target path> <2 distfiles dir> [3 stage]"
+  echo
+  echo "  Stage 0.1 - OpenMP"
+  echo "  Stage 0.2 - lzma"
+  echo "  Stage 1.1 - boost"
+  echo "  Stage 1.2 - jpeg"
+  echo "  Stage 1.3 - tiff"
+  echo "  Stage 1.4 - png"
+  echo "  Stage 1.6 - ilmbase"
+  echo "  Stage 1.7 - OpenEXR"
+  echo "  Stage 2.1 - OpenImageIO"
+  echo "  Stage 4.1 - Embree"
+  echo "  Stage 4.2 - C-blosc"
+  echo "  Stage 4.3 - TBB"
+  echo "  Stage 4.4 - OpenCL"
+  echo
+  exit 1
 fi
 
 ROOT=${PWD}
@@ -78,12 +78,12 @@ mkdir -p $WORK 2>/dev/null
 # compilation prechecks
 echo -ne "\033]0;Preparing\007"
 if [[ ! $STAGE ]] ; then
-    S=`cat $TARGET/stage 2>/dev/null`
-    if [[ ! $S ]] ; then
-        STAGE=0
-    else
-        STAGE=$S
-    fi
+  S=`cat $TARGET/stage 2>/dev/null`
+  if [[ ! $S ]] ; then
+    STAGE=0
+  else
+    STAGE=$S
+  fi
 fi
 
 PYTHON_LIB=`find $TARGET -name 'libpython*'`
@@ -96,216 +96,211 @@ echo
 # STAGE 0.1 -- OpenMP
 NEXT=0.2
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-    begin_stage openmp openmp*.tar.xz
+  begin_stage openmp openmp*.tar.xz
 
-    mkdir build && cd build
+  mkdir build && cd build
 
-    echo " * Preparing OpenMP build"
-    if cmake -DLIBOMP_ENABLE_SHARED=OFF .. -DCMAKE_INSTALL_PREFIX=$TARGET ; then
-        echo " * OpenMP prepared successfully"
-    else
-        echo " !!! OpenMP cmake failed"
-        exit 1
-    fi
+  echo " * Preparing OpenMP build"
+  if cmake -DLIBOMP_ENABLE_SHARED=OFF .. -DCMAKE_INSTALL_PREFIX=$TARGET ; then
+    echo " * OpenMP prepared successfully"
+  else
+    echo " !!! OpenMP cmake failed"
+    exit 1
+  fi
 
-    sleep $PAUSE
+  sleep $PAUSE
 
-    if make $MAKEOPTS && make install ; then
-        echo " * OpenMP built successfully"
-    else
-        echo " !!! OpenMP build failed"
-        exit 1
-    fi
+  if make $MAKEOPTS && make install ; then
+    echo " * OpenMP built successfully"
+  else
+    echo " !!! OpenMP build failed"
+    exit 1
+  fi
 
-    complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 0.1 -- lzma
 NEXT=0.4
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-    begin_stage lzma xz*.tar.gz
+  begin_stage lzma xz*.tar.gz
 
-    if ! ./configure --enable-static --disable-shared --disable-scripts --disable-xz \
-    --disable-xzdec --disable-lzmadec --disable-lzmainfo --disable-lzma-links \
-    --prefix=$TARGET ; then
-        echo " !!! lzma configuration failed"
-        exit 1
-    fi
-    sleep $PAUSE
-    if make $MAKEOPTS && make install ; then
-        echo " * lzma compiled and installed successfully"
-    else
-        echo " !!! lzma compilation failed"
-        exit 1
-    fi
+  if ! ./configure --enable-static --disable-shared --disable-scripts --disable-xz \
+  --disable-xzdec --disable-lzmadec --disable-lzmainfo --disable-lzma-links \
+  --prefix=$TARGET ; then
+    echo " !!! lzma configuration failed"
+    exit 1
+  fi
+  sleep $PAUSE
+  if make $MAKEOPTS && make install ; then
+    echo " * lzma compiled and installed successfully"
+  else
+    echo " !!! lzma compilation failed"
+    exit 1
+  fi
 
-    complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 1.1 -- Boost
 NEXT=1.2
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage boost boost*.tar.gz
+  begin_stage boost boost*.tar.gz
 
-	PYVER=`python3 --version 2>&1 | cut -d' ' -f2 | cut -d '.' -f'1 2'`
-	echo " * Compiling boost for python-${PYVER}"
-	sleep 1
-	if ! ./bootstrap.sh --without-icu --prefix=$TARGET/boost \
-	--with-python=/usr/bin/python${PYVER} \
-	--with-python-root=`python${PYVER} -c "import sys; print(sys.prefix)"` ; then
-		echo " !!! Boost bootstrap failed"
-		exit 1
-	fi
-	if ./b2 $MAKEOPTS -aq \
-		$CONFIGOPTS --prefix=$TARGET --layout=system --with-date_time --with-filesystem \
-		--with-iostreams --with-locale --with-program_options --with-python --with-regex \
-		--with-serialization --with-system --with-thread --with-chrono \
-		threading=multi link=static \
-		release install ; then
-		# Fix boost python lib name
-		mv $TARGET/lib/libboost_python*.a $TARGET/lib/libboost_python.a
-		echo " * Boost compiled and installed successfully"
-	else
-		echo " !!! Boost compilation failed"
-		exit 1
-	fi
+  PYVER=`python3 --version 2>&1 | cut -d' ' -f2 | cut -d '.' -f'1 2'`
+  echo " * Compiling boost for python-${PYVER}"
+  sleep 1
+  if ! ./bootstrap.sh --without-icu --prefix=$TARGET/boost \
+  --with-python=/usr/bin/python${PYVER} \
+  --with-python-root=`python${PYVER} -c "import sys; print(sys.prefix)"` ; then
+    echo " !!! Boost bootstrap failed"
+    exit 1
+  fi
+  if ./b2 $MAKEOPTS -aq \
+    $CONFIGOPTS --prefix=$TARGET --layout=system --with-date_time --with-filesystem \
+    --with-iostreams --with-locale --with-program_options --with-python --with-regex \
+    --with-serialization --with-system --with-thread --with-chrono \
+    threading=multi link=static \
+    release install ; then
+    # Fix boost python lib name
+    mv $TARGET/lib/libboost_python*.a $TARGET/lib/libboost_python.a
+    echo " * Boost compiled and installed successfully"
+  else
+    echo " !!! Boost compilation failed"
+    exit 1
+  fi
 
-	complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 1.2 -- Jpeg
 NEXT=1.3
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage jpeg jpeg*.tar.gz
+  begin_stage jpeg jpeg*.tar.gz
 
-	if ! ./configure --enable-static --prefix=$TARGET ; then
-		echo " !!! Jpeg configuration failed"
-		exit 1
-	fi
-	sleep $PAUSE
-	if make $MAKEOPTS && cp -vf .libs/libjpeg.a $TARGET/lib && \
-	 cp -vf *.h $TARGET/include ; then
-		echo " * Jpeg compiled and installed successfully"
-	else
-		echo " !!! Jpeg compilation failed"
-		exit 1
-	fi
+  if ! ./configure --enable-static --prefix=$TARGET ; then
+    echo " !!! Jpeg configuration failed"
+    exit 1
+  fi
+  sleep $PAUSE
+  if make $MAKEOPTS && cp -vf .libs/libjpeg.a $TARGET/lib && \
+   cp -vf *.h $TARGET/include ; then
+    echo " * Jpeg compiled and installed successfully"
+  else
+    echo " !!! Jpeg compilation failed"
+    exit 1
+  fi
 
-	complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 1.3 -- Tiff
 NEXT=1.4
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage tiff tiff*.tar.gz
+  begin_stage tiff tiff*.tar.gz
 
-	if ! ./configure --enable-static --disable-shared --disable-jbig $CONFIGOPTS --prefix=$TARGET ; then
-		echo " !!! TIFF configuration failed"
-		exit 1
-	fi
-	sleep $PAUSE
-	if make $MAKEOPTS && make install ; then
-		echo " * TIFF compiled and installed successfully"
-	else
-		echo " !!! TIFF compilation failed"
-		exit 1
-	fi
+  if ! ./configure --enable-static --disable-shared --disable-jbig $CONFIGOPTS --prefix=$TARGET ; then
+    echo " !!! TIFF configuration failed"
+    exit 1
+  fi
+  sleep $PAUSE
+  if make $MAKEOPTS && make install ; then
+    echo " * TIFF compiled and installed successfully"
+  else
+    echo " !!! TIFF compilation failed"
+    exit 1
+  fi
 
-	complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 1.4 -- PNG
 NEXT=1.6
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage png libpng*.tar.gz
+  begin_stage png libpng*.tar.gz
 
-	# --with-libpng-prefix=lux_
-	if ! ./configure --enable-static --disable-shared $CONFIGOPTS --prefix=$TARGET ; then
-		echo " !!! PNG configuration failed"
-		exit 1
-	fi
-	sleep $PAUSE
-	if make $MAKEOPTS && make install && cd $TARGET/include && ln -vs libpng* libpng ; then
-		echo " * PNG compiled and installed successfully"
-	else
-		echo " !!! PNG compilation failed"
-		exit 1
-	fi
+  if ! ./configure --enable-static --disable-shared $CONFIGOPTS --prefix=$TARGET ; then
+    echo " !!! PNG configuration failed"
+    exit 1
+  fi
+  sleep $PAUSE
+  if make $MAKEOPTS && make install && cd $TARGET/include && ln -vs libpng* libpng ; then
+    echo " * PNG compiled and installed successfully"
+  else
+    echo " !!! PNG compilation failed"
+    exit 1
+  fi
 
-	complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 1.6 -- IlmBase
 NEXT=1.7
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage ilmbase ilmbase*.tar.gz
+  begin_stage ilmbase ilmbase*.tar.gz
 
-	if ! ./configure --enable-static --disable-shared $CONFIGOPTS --prefix=$TARGET ; then
-		echo " !!! ilmbase configuration failed"
-		exit 1
-	fi
-	sleep $PAUSE
-	if make $MAKEOPTS && make install ; then
-		echo " * ilmbase compiled and installed successfully"
-	else
-		echo " !!! ilmbase compilation failed"
-		exit 1
-	fi
+  if ! ./configure --enable-static --disable-shared $CONFIGOPTS --prefix=$TARGET ; then
+    echo " !!! ilmbase configuration failed"
+    exit 1
+  fi
+  sleep $PAUSE
+  if make $MAKEOPTS && make install ; then
+    echo " * ilmbase compiled and installed successfully"
+  else
+    echo " !!! ilmbase compilation failed"
+    exit 1
+  fi
 
-	complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 1.7 -- OpenEXR
 NEXT=1.8
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage openexr openexr*.tar.gz
+  begin_stage openexr openexr*.tar.gz
 
-	if ! ./configure --enable-static --disable-shared --with-ilmbase-prefix=$TARGET \
-	$CONFIGOPTS --prefix=$TARGET ; then
-		echo " !!! openexr configuration failed"
-		exit 1
-	fi
-	sleep $PAUSE
-	if make $MAKEOPTS && make install ; then
-		echo " * openexr compiled and installed successfully"
-	else
-		echo " !!! openexr compilation failed"
-		exit 1
-	fi
+  if ! ./configure --enable-static --disable-shared \
+    --with-ilmbase-prefix=$TARGET $CONFIGOPTS --prefix=$TARGET ; then
+    echo " !!! openexr configuration failed"
+    exit 1
+  fi
+  sleep $PAUSE
+  if make $MAKEOPTS && make install ; then
+    echo " * openexr compiled and installed successfully"
+  else
+    echo " !!! openexr compilation failed"
+    exit 1
+  fi
 
-	complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 2.1 -- OpenImageIO
 NEXT=4.1
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage openimageio oiio*.tar.gz
+  begin_stage openimageio oiio*.tar.gz
 
-	echo " * Patching OpenImageIO"
-	cp -vf $DIST/oiio-1.8.11-plugin.cpp src/libutil/plugin.cpp
-	cp -vf $DIST/oiio-1.8.11-externalpackages.cmake src/cmake/externalpackages.cmake
-	if CMAKE_PREFIX_PATH=$TARGET make $MAKEOPTS BOOST_HOME=$TARGET ILMBASE_HOME=$TARGET \
-		VERBOSE=0 USE_FFMPEG=0 \
-		EMBEDPLUGINS=1 USE_OPENGL=0 USE_QT=0 USE_GIF=0 USE_OPENJPEG=0 USE_OPENSSL=0 \
-		USE_FIELD3D=0 USE_OCIO=0 USE_OPENCV=0 USE_PYTHON=0 \
-		BUILDSTATIC=1 LINKSTATIC=1 OIIO_BUILD_TOOLS=0 OIIO_BUILD_TESTS=0 \
-		STOP_ON_WARNING=0 ; then
-		echo " * openimageio compiled successfully"
-	else
-		echo " !!! openimageio compilation failed"
-		exit 1
-	fi
-	echo " * Installing openimageio library and headers"
-	sleep $PAUSE
-	if cp -vr dist/macos*/* $TARGET && cd $TARGET/lib ; then
-        # && \
-	#mv -v libOpenImageIO.a libOpenImageIOBase.a && \
-	#ar -rcT libOpenImageIO.a libOpenImageIOBase.a libpng.a libjpeg.a libtiff.a libHalf.a \
-	#libIex.a libIexMath.a libIlmImf.a libIlmThread.a libImath.a liblzma.a ; then
-        echo " * openimageio installed successfully"
+  echo " * Patching OpenImageIO"
+  cp -vf $DIST/oiio-1.8.11-plugin.cpp src/libutil/plugin.cpp
+  cp -vf $DIST/oiio-1.8.11-externalpackages.cmake src/cmake/externalpackages.cmake
+  if CMAKE_PREFIX_PATH=$TARGET make $MAKEOPTS BOOST_HOME=$TARGET \
+    ILMBASE_HOME=$TARGET VERBOSE=0 USE_FFMPEG=0 \
+    EMBEDPLUGINS=1 USE_OPENGL=0 USE_QT=0 USE_GIF=0 USE_OPENJPEG=0 USE_OPENSSL=0 \
+    USE_FIELD3D=0 USE_OCIO=0 USE_OPENCV=0 USE_PYTHON=0 \
+    BUILDSTATIC=1 LINKSTATIC=1 OIIO_BUILD_TOOLS=0 OIIO_BUILD_TESTS=0 \
+    STOP_ON_WARNING=0 ; then
+    echo " * openimageio compiled successfully"
+  else
+    echo " !!! openimageio compilation failed"
+    exit 1
+  fi
+  echo " * Installing openimageio library and headers"
+  sleep $PAUSE
+  if cp -vr dist/macos*/* $TARGET && cd $TARGET/lib ; then
+      echo " * openimageio installed successfully"
     else
-        echo " !!! openimageio installation failed"
-        exit 1
+      echo " !!! openimageio installation failed"
+      exit 1
     fi
 
     complete_stage $NEXT
@@ -314,63 +309,64 @@ fi
 # STAGE 4.1 -- Embree
 NEXT=4.2
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage Embree embree-*.tar.gz
+  begin_stage Embree embree-*.tar.gz
 
-	cp -v ${ROOT}/utils/embree-install.sh .
+  cp -v ${ROOT}/utils/embree-install.sh .
 
     sleep 1
     if ./embree-install.sh $TARGET ; then
-        echo " * Embree library and headers installed successfully"
+      echo " * Embree library and headers installed successfully"
     else
-        echo " !!! Embree library and headers installation failed"
-        exit 1
+      echo " !!! Embree library and headers installation failed"
+      exit 1
     fi
 
-	complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 4.2 -- C-blosc
 NEXT=4.3
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-	begin_stage C-blosc c-blosc-*.tar.gz
+  begin_stage C-blosc c-blosc-*.tar.gz
 
-	mkdir build && cd build
+  mkdir build && cd build
 
-	if cmake -DCMAKE_INSTALL_PREFIX=$TARGET -DBUILD_SHARED=OFF -DBUILD_TESTS=OFF -DBUILD_BENCHMARKS=OFF .. && cmake --build . --target install ; then
-		echo " * C-blosc compiled successfully"
-	else
-		echo " !!! C-blosc compilation failed"
-		exit 1
-	fi
+  if cmake -DCMAKE_INSTALL_PREFIX=$TARGET -DBUILD_SHARED=OFF -DBUILD_TESTS=OFF -DBUILD_BENCHMARKS=OFF .. && cmake --build . --target install ; then
+    echo " * C-blosc compiled successfully"
+  else
+    echo " !!! C-blosc compilation failed"
+    exit 1
+  fi
 
-	complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # STAGE 4.3 -- TBB
 NEXT=4.4
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
-    begin_stage TBB tbb*_mac.tgz
+  begin_stage TBB tbb*_mac.tgz
 
-    cp -v ${ROOT}/utils/tbb-install.sh .
+  cp -v ${ROOT}/utils/tbb-install.sh .
 
-    sleep 1
-    if ./tbb-install.sh $TARGET ; then
-        echo " * TBB library and headers installed successfully"
-    else
-        echo " !!! TBB library and headers installation failed"
-        exit 1
-    fi
+  sleep 1
+  if ./tbb-install.sh $TARGET ; then
+    echo " * TBB library and headers installed successfully"
+  else
+    echo " !!! TBB library and headers installation failed"
+    exit 1
+  fi
 
-    complete_stage $NEXT
+  complete_stage $NEXT
 fi
 
 # Stage 4.4 -- OpenCL
 NEXT=5
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
     if cp -R ${DIST}/OpenCL ${TARGET}/include ; then
-        echo " * OpenCL header installed successfully"
+      echo " * OpenCL header installed successfully"
     else
-        echo " !!! OpenCL header installation failed"
+      echo " !!! OpenCL header installation failed"
+			exit 1
     fi
 fi
 
