changes to compile on 10.13

diff --git a/build_deps b/build_deps
--- a/build_deps
+++ b/build_deps
@@ -52,6 +52,7 @@ if [[ ! ${2} ]] ; then
   echo "  Stage 4.2 - C-blosc"
   echo "  Stage 4.3 - TBB"
   echo "  Stage 4.4 - OpenCL"
+  echo "  Stage 5.5 - OpenImageDenoise"
   echo
   exit 1
 fi
@@ -189,7 +190,7 @@ NEXT=1.3
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
   begin_stage jpeg jpeg*.tar.gz
 
-  if ! ./configure --enable-static --prefix=$TARGET ; then
+  if ! ./configure --enable-static --disable-shared --prefix=$TARGET ; then
     echo " !!! Jpeg configuration failed"
     exit 1
   fi
@@ -210,7 +211,7 @@ NEXT=1.4
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
   begin_stage tiff tiff*.tar.gz
 
-  if ! ./configure --enable-static --disable-shared --disable-jbig $CONFIGOPTS --prefix=$TARGET ; then
+  if ! ./configure --disable-static --disable-jbig $CONFIGOPTS --prefix=$TARGET ; then
     echo " !!! TIFF configuration failed"
     exit 1
   fi
@@ -298,7 +299,7 @@ if [[ $STAGE && $STAGE < $NEXT ]] ; then
     ILMBASE_HOME=$TARGET VERBOSE=0 USE_FFMPEG=0 \
     EMBEDPLUGINS=1 USE_OPENGL=0 USE_QT=0 USE_GIF=0 USE_OPENJPEG=0 USE_OPENSSL=0 \
     USE_FIELD3D=0 USE_OCIO=0 USE_OPENCV=0 USE_PYTHON=0 \
-    BUILDSTATIC=1 LINKSTATIC=1 OIIO_BUILD_TOOLS=0 OIIO_BUILD_TESTS=0 \
+    BUILDSTATIC=0 LINKSTATIC=1 OIIO_BUILD_TOOLS=0 OIIO_BUILD_TESTS=0 \
     STOP_ON_WARNING=0 ; then
     echo " * openimageio compiled successfully"
   else
@@ -371,7 +372,7 @@ if [[ $STAGE && $STAGE < $NEXT ]] ; then
 fi
 
 # Stage 4.4 -- OpenCL
-NEXT=5
+NEXT=5.5
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
     if cp -R ${DIST}/OpenCL ${TARGET}/include ; then
       echo " * OpenCL header installed successfully"
@@ -379,6 +380,23 @@ if [[ $STAGE && $STAGE < $NEXT ]] ; then
       echo " !!! OpenCL header installation failed"
 			exit 1
     fi
+fi
+
+# STAGE 5.5 -- OpenImageDenoise
+NEXT=6
+if [[ $STAGE && $STAGE < $NEXT ]] ; then
+  begin_stage OpenImageDenoise oidn*.tar.gz
+
+  mkdir build && cd build
+
+  if cmake -DCMAKE_INSTALL_PREFIX=$TARGET .. && make $MAKEOPTS && make install ; then
+    echo " * OpenImageDenoise installed successfully"
+  else
+    echo " !!! OpenImageDenoise compilation failed"
+    exit 1
+  fi
+
+  complete_stage $NEXT
 fi
 
 mkdir -p ${TARGET}/lib/Release
